language:
- python

python:
- '3.6'

install:
- pip install -r requirements.txt

script:
- nosetests

deploy:

  provider: heroku
  
  api_key:
  
    secure: dF2BwejpCMJVw9N+ltCzhgp49NgUDHQ7EqnoH47Qc4tUlXEJZXjriVOArSvViWzmr68n/HrrYCJVYXaTGBFN53+dRpKuHx5C+GTtw9El9wLxVEF0wBrXZd9q7pKVPqw3qQOcDRyN0YWTlaw1XPnr6F4vGHu2sVE2fRhNueCvjiBKV2HWcA+v/mSu0TodfU/zxUMM6KZ+Xq48h00XiR4lnrqoZDrNj3NBlWgE7ZaL15YZOkvh2hYpZOKA1JRulyQLe0cPTGtdhjrZtNKPYma8cQ6GyivaRz051jn/rx0RBloYJGivxKVBPEmWDJVPYSW3GMRhJD/PUyvcTws2kqFCI8Yl/GtN8C3JfDCbUN9NQmYm59ZN9+yv+ZDADRSavKeSS1eZzmfYEqhMmpnun3CIjakaJPl1Nxdo5YMwLjwbimcfhaRhEvHAxUq9LpaCtyahM323OYyhN3sGPgqtTduLhgfTGrFIXg0GtSPk4TOZAmma7RV7/i0RfCtYm0pyFnM3K7OKxeo7RLBOBtufRSu3w9kSxDafNLAfYLWM9+ODX34k+ZNozKi3mepjLRHhbrxo5JgT/wkDEjjbNnZgJOYaMwl2kZf0EqeFVdn7+TH0euNTPQfcdSKmmdDsTPFz4AkB3n1+hGoXQXGg2nT+Omwb7oN8HB8O+Wygojw2TqBKZW8=
    
  app: peaceful-depths-74245
  
  on:
    branch: master
    python: '3.6'
    repo: MaciejSwierad/FlaskTaskr
